FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

WORKDIR /workspace

RUN apk add --no-cache bash

COPY *.csproj ./
RUN dotnet restore

COPY . .

EXPOSE 5000

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]
