version: "3.8"

services:
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.prod

  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env.prod
