version: "3.8"

services:
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/src
    env_file:
      - ./backend/.env.dev

  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/workspace
    env_file:
      - ./frontend/.env.dev
