version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: ./Docker/Frontend/Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app

  backend:
    build:
      context: .
      dockerfile: ./Docker/Backend/Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./MyApp.Api:/src/MyApp.Api

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
