version: '3.8'

services:
  frontend:
    image: oven/bun:alpine
    container_name: nextjs_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "bun install && bun dev"
    depends_on:
      - backend

  backend:
    image: oven/bun:alpine
    container_name: json_server_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: sh -c "json-server --watch db.json --port 3001"
    depends_on:
      - db

#   db:
#     image: postgres:latest
#     container_name: postgres_container
#     environment:
#       POSTGRES_USER: your_user
#       POSTGRES_PASSWORD: your_password
#       POSTGRES_DB: your_db
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data: